@startuml
class Animal {
def __init__(): \n     super().__init__()
}
class Mummal {
def __init__(): \n     super().__init__()
}
class Bird {
def __init__(): \n     super().__init__()
}
class Platypus {
def __init__(): \n     super().__init__()
}
Animal <|-- Mummal
Animal <|-- Bird
Bird <|-- Platypus
Mummal <|-- Platypus

@enduml