@startuml
control function_1
control function_2
collections CPU

function_1 -> CPU
activate CPU
function_2 ->x CPU
note right: func2 request but we \nare busy with func1
CPU -> CPU: wait for io
|||
CPU --> function_1
deactivate CPU
CPU -> CPU: ready to get next func
activate CPU
CPU --> function_2
deactivate CPU
@enduml