@startuml
control func1
control func2
collections CPU

func1 -> CPU
activate CPU
func2 -> CPU
note right: switching between func1 \nand func2 - at least twice \nas much execution time
activate CPU
CPU --> func2
deactivate CPU
|||
|||
CPU --> func1
deactivate CPU
@enduml